apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REDIS_URL: "redis://redis-service:6379"
  PORT: "3000"
  METRICS_PORT: "3001"
  JWT_SECRET: "my-super-secret-key-12345"
  RATE_LIMIT_MAX: "1000"
  CORS_ORIGIN: "http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:5173"
