apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-b-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: service-b
  endpoints:
  - port: metrics
    path: /metrics
    interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-c-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: service-c
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
